import { ImageResponse } from '@vercel/og';
import { NextRequest } from 'next/server';

export const config = {
  runtime: 'edge',
};

export default function handler(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const numbers = searchParams.get('numbers')?.split(',').map(Number) || [];

    return new ImageResponse(
      (
        <div
          style={{
            height: '100%',
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#1e293b', // 어두운 배경색
            fontFamily: 'Inter, sans-serif',
          }}
        >
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: 'white',
              borderRadius: '16px',
              padding: '40px',
            }}
          >
            <h1 style={{ fontSize: '36px', fontWeight: 'bold', color: '#1e293b', marginBottom: '24px' }}>
              Unlucky Lotto Numbers
            </h1>
            <div style={{ display: 'flex', gap: '16px', marginBottom: '24px' }}>
              {numbers.map((number, index) => (
                <div
                  key={index}
                  style={{
                    backgroundColor: '#3b82f6', // primary 색상
                    color: 'white',
                    width: '80px',
                    height: '80px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '32px',
                    fontWeight: 'bold',
                  }}
                >
                  {number}
                </div>
              ))}
            </div>
            <p style={{ fontSize: '24px', color: '#64748b' }}>
              Generated by Unlucky Lotto Generator
            </p>
          </div>
        </div>
      ),
      {
        width: 1200,
        height: 630,
      },
    );
  } catch (e: unknown) {
    console.log(`${e instanceof Error ? e.message : 'An unknown error occurred'}`);
    return new Response(`Failed to generate the image`, {
      status: 500,
    });
  }
}